name: Annie
title: Annie
url: https://annieapp.co
plugins:
  - jekyll-github-metadata
  - jekyll-redirect-from
  - jekyll-sitemap
repository: annieapp/annie
description: Annie is a small, lightweight, and fast analytics program for website owners.
twitter: NerdyJumbo
