task:
  container:
    image: python:latest
  script: echo hi

deploy_task:
  only_if: $CIRRUS_BRANCH == 'master'
  container:
    image: squidfunk/mkdocs-material:4.3.1
  install_script: pip install --upgrade pymdown-extensions
  deploy_script: |
    git remote set-url origin https://$DEPLOY_TOKEN@github.com/annieapp/annie/
    mkdocs gh-deploy --force --remote-branch gh-pages
