deploy_task:
  only_if: $CIRRUS_BRANCH == 'master'
  skip: "!changesInclude('.cirrus.yml', 'mkdocs.yml', 'docs/**')"
  container:
    image: squidfunk/mkdocs-material:4.3.1
  install_script: pip install --upgrade pymdown-extensions
  env:
    DEPLOY_TOKEN: ENCRYPTED[8b719b51d75561d87baa92c15925d77ddce4a78bd31b1b87b48f1ca0931bd7b968357edf401e0ecbc2a0e8c49ea8cbff]
  deploy_script: |
    git config --global user.name "Cirrus CI"
    git config --global user.email "support@rdil.rocks"
    git remote set-url origin https://$DEPLOY_TOKEN@github.com/annieapp/annie/
    mkdocs gh-deploy --force --remote-branch gh-pages

frontend_tests_task:
  container:
    image: ruby:latest
  env:
    JEKYLL_ENV: production
    NOKOGIRI_USE_SYSTEM_LIBRARIES: false
  bootstrap_script: gem install bundler
  bundler_cache:
    folder: /usr/local/bundle
    fingerprint_script: |
      ruby -v
      cat frontend/Gemfile
    populate_script: cd frontend && bundler
  build_and_test_script: cd frontend && bundler exec jekyll build
  site_build_artifacts:
    path: frontend/_site/**/**

server_beta_task:
  only_if: $CIRRUS_BRANCH != 'gh-pages'
  container:
    image: python:slim
  install_script: python3 -m pip install --upgrade --user setuptools wheel
  build_script: python3 setup.py sdist
  download_artifacts:
    path: dist/**

server_headless_tests_task:
  osx_instance:
    image: mojave-xcode-10.2
  install_dependencies_script: |
    brew install python
    python3 -m pip install --upgrade --user -r requirements.txt
    brew install phantomjs
  script: python3 -m xmlrunner tests
  unittest_results_artifacts:
    path: ./*.xml
    format: junit
