deploy_task:
  only_if: $CIRRUS_BRANCH == 'master'
  skip: "!changesInclude('.cirrus.yml', '*mkdocs.yml', 'docs/**')"
  container:
    image: squidfunk/mkdocs-material:4.3.1
  install_script: pip install --upgrade pymdown-extensions
  env:
    DEPLOY_TOKEN: ENCRYPTED[8b719b51d75561d87baa92c15925d77ddce4a78bd31b1b87b48f1ca0931bd7b968357edf401e0ecbc2a0e8c49ea8cbff]
  deploy_script: |
    git config --global user.name "Cirrus CI"
    git config --global user.email "support@rdil.rocks"
    git remote set-url origin https://$DEPLOY_TOKEN@github.com/annieapp/annie/
    mkdocs gh-deploy --force --remote-branch gh-pages

frontend_tests_task:
  container:
    image: ruby:latest
  env:
    JEKYLL_ENV: production
    NOKOGIRI_USE_SYSTEM_LIBRARIES: false
  bootstrap_script: |
    gem install bundler
    cd frontend
  bundler_cache:
    folder: /usr/local/bundle
    fingerprint_script: |
      ruby -v
      cat Gemfile
    populate_script: bundler
  build_and_test_script: bundler exec jekyll build
  site_build_artifacts:
    path: _site/**/**
