site_name: Annie Docs

theme:
  name: 'material'
  palette:
    primary: 'pink'
    accent: 'pink'
  feature:
    tabs: false
  logo: 'images/logo512x512.png'
  favicon: 'assets/images/favicon.ico'

repo_name: 'annieapp/annie'
repo_url: 'https://github.com/annieapp/annie'

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

site_description: Annie is a small, lightweight, and fast analytics program for website owners.
site_url: https://docs.annieapp.co
site_author: Annie Team
copyright: Copyright (©) Annie 2019-present
remote_branch: master

extra:
  social:
    - type: 'github'
      link: 'https://github.com/annieapp'
  manifest: 'manifest.json'

nav:
  - Home: index.md
  - 'API': api.md
  - 'Self Hosting (Optional)': selfhost.md
  - 'Developer Portal': development.md
  - 'Implementation Examples': examples.md
  - 'FAQ': faq.md
  - 'Security Policy': security.md
  - 'Contributor Code of Conduct': code_of_conduct.md
